"""add Department

Revision ID: 016c70440b9f
Revises: 2a15a690526a
Create Date: 2025-06-15 14:40:28.830602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016c70440b9f'
down_revision = '2a15a690526a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
